version: '2'
services:
  xslt-api:
    container_name: xslt-api-python
    build: .
    working_dir: /usr/src/app
    command: flask run --host=0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
    # depends_on:
    #   - redis
    # external_links:
    #   - redis
  #   network_mode: bridge
  # redis:
  #   container_name: redis
  #   image: redis:3.2.10-alpine
  #   network_mode: bridge
